FROM ubuntu:22.04 AS base

RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    python3-pip \
    wine64 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/BotCopier

COPY . .
RUN pip3 install --no-cache-dir .

FROM base AS serve-model
EXPOSE 8000
CMD ["botcopier-serve-model", "--host", "0.0.0.0", "--port", "8000"]

FROM base AS build
CMD ["bash"]
