FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    python3-pip \
    wine64 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/BotCopier

COPY . .
RUN pip3 install --no-cache-dir .

CMD ["bash"]
