site_name: BotCopier
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Architecture: architecture.md
  - Data Flow: data_flow.md
  - Model Registry: model_registry.md
  - CLI Usage: cli_usage.md
  - API Reference: api.md
  - Contributing:
      - Overview: contributing.md
      - Coding Standards: coding_standards.md
      - Testing: testing.md
  - Troubleshooting: troubleshooting.md
  - Guides:
      - Hardware-aware Training: hardware-training.md
      - Feature Plugins: feature_plugins.md
  - Tutorials:
      - Data Loading and Feature Engineering: data_loading_tutorial.md
markdown_extensions:
  - admonition
  - pymdownx.superfences
plugins:
  - mkdocstrings
