# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated_buffer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'federated_buffer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66\x65\x64\x65rated_buffer.proto\x12\tfederated\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n\x0f\x45xperienceBatch\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x90\x01\n\x10\x45xperienceBuffer\x12<\n\x06Upload\x12\x1a.federated.ExperienceBatch\x1a\x16.google.protobuf.Empty\x12>\n\x08\x44ownload\x12\x16.google.protobuf.Empty\x1a\x1a.federated.ExperienceBatchb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_buffer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXPERIENCEBATCH']._serialized_start=66
  _globals['_EXPERIENCEBATCH']._serialized_end=97
  _globals['_EXPERIENCEBUFFER']._serialized_start=100
  _globals['_EXPERIENCEBUFFER']._serialized_end=244
# @@protoc_insertion_point(module_scope)
