# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: log_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'log_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import trade_event_pb2 as trade__event__pb2
import metric_event_pb2 as metric__event__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11log_service.proto\x12\x04tbot\x1a\x11trade_event.proto\x1a\x12metric_event.proto\x1a\x1bgoogle/protobuf/empty.proto2{\n\nLogService\x12\x34\n\x08LogTrade\x12\x10.tbot.TradeEvent\x1a\x16.google.protobuf.Empty\x12\x37\n\nLogMetrics\x12\x11.tbot.MetricEvent\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGSERVICE']._serialized_start=95
  _globals['_LOGSERVICE']._serialized_end=218
# @@protoc_insertion_point(module_scope)
