# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metric_event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12metric_event.proto\x12\x04tbot\"\xf1\x01\n\x0bMetricEvent\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\r\n\x05magic\x18\x02 \x01(\x05\x12\x10\n\x08win_rate\x18\x03 \x01(\x01\x12\x12\n\navg_profit\x18\x04 \x01(\x01\x12\x13\n\x0btrade_count\x18\x05 \x01(\x05\x12\x10\n\x08\x64rawdown\x18\x06 \x01(\x01\x12\x0e\n\x06sharpe\x18\x07 \x01(\x01\x12\x19\n\x11\x66ile_write_errors\x18\x08 \x01(\x05\x12\x15\n\rsocket_errors\x18\t \x01(\x05\x12\x1c\n\x14\x62ook_refresh_seconds\x18\n \x01(\x05\x12\x18\n\x10var_breach_count\x18\x0b \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metric_event_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METRICEVENT._serialized_start=29
  _METRICEVENT._serialized_end=270
# @@protoc_insertion_point(module_scope)
