# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: observer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import trade_event_pb2 as trade__event__pb2
import metric_event_pb2 as metric__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eobserver.proto\x12\x04tbot\x1a\x11trade_event.proto\x1a\x12metric_event.proto\"|\n\x0fObserverMessage\x12\x16\n\x0eschema_version\x18\x01 \x01(\t\x12!\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x10.tbot.TradeEventH\x00\x12#\n\x06metric\x18\x03 \x01(\x0b\x32\x11.tbot.MetricEventH\x00\x42\t\n\x07payloadb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'observer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBSERVERMESSAGE._serialized_start=63
  _OBSERVERMESSAGE._serialized_end=187
# @@protoc_insertion_point(module_scope)
