# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: observer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'observer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import trade_event_pb2 as trade__event__pb2
from . import metrics_pb2 as metrics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eobserver.proto\x12\x04tbot\x1a\x11trade_event.proto\x1a\rmetrics.proto\"x\n\x0fObserverMessage\x12\x16\n\x0eschema_version\x18\x01 \x01(\t\x12!\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x10.tbot.TradeEventH\x00\x12\x1f\n\x06metric\x18\x03 \x01(\x0b\x32\r.tbot.MetricsH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'observer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBSERVERMESSAGE']._serialized_start=58
  _globals['_OBSERVERMESSAGE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
