// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: predict.proto

#include "predict.pb.h"
#include "predict.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace tbot {

static const char* PredictService_method_names[] = {
  "/tbot.PredictService/Predict",
};

std::unique_ptr< PredictService::Stub> PredictService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PredictService::Stub> stub(new PredictService::Stub(channel, options));
  return stub;
}

PredictService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Predict_(PredictService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PredictService::Stub::Predict(::grpc::ClientContext* context, const ::tbot::PredictRequest& request, ::tbot::PredictResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::tbot::PredictRequest, ::tbot::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Predict_, context, request, response);
}

void PredictService::Stub::async::Predict(::grpc::ClientContext* context, const ::tbot::PredictRequest* request, ::tbot::PredictResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::tbot::PredictRequest, ::tbot::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Predict_, context, request, response, std::move(f));
}

void PredictService::Stub::async::Predict(::grpc::ClientContext* context, const ::tbot::PredictRequest* request, ::tbot::PredictResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Predict_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::tbot::PredictResponse>* PredictService::Stub::PrepareAsyncPredictRaw(::grpc::ClientContext* context, const ::tbot::PredictRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::tbot::PredictResponse, ::tbot::PredictRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Predict_, context, request);
}

::grpc::ClientAsyncResponseReader< ::tbot::PredictResponse>* PredictService::Stub::AsyncPredictRaw(::grpc::ClientContext* context, const ::tbot::PredictRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPredictRaw(context, request, cq);
  result->StartCall();
  return result;
}

PredictService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PredictService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PredictService::Service, ::tbot::PredictRequest, ::tbot::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PredictService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::tbot::PredictRequest* req,
             ::tbot::PredictResponse* resp) {
               return service->Predict(ctx, req, resp);
             }, this)));
}

PredictService::Service::~Service() {
}

::grpc::Status PredictService::Service::Predict(::grpc::ServerContext* context, const ::tbot::PredictRequest* request, ::tbot::PredictResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace tbot

