# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predict.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\x12\x04tbot\"\"\n\x0ePredictRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x01\"%\n\x0fPredictResponse\x12\x12\n\nprediction\x18\x01 \x01(\x01\x32H\n\x0ePredictService\x12\x36\n\x07Predict\x12\x14.tbot.PredictRequest\x1a\x15.tbot.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=23
  _globals['_PREDICTREQUEST']._serialized_end=57
  _globals['_PREDICTRESPONSE']._serialized_start=59
  _globals['_PREDICTRESPONSE']._serialized_end=96
  _globals['_PREDICTSERVICE']._serialized_start=98
  _globals['_PREDICTSERVICE']._serialized_end=170
# @@protoc_insertion_point(module_scope)
