# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trade_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trade_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11trade_event.proto\x12\x04tbot\"\x90\x04\n\nTradeEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x05\x12\x12\n\nevent_time\x18\x02 \x01(\t\x12\x13\n\x0b\x62roker_time\x18\x03 \x01(\t\x12\x12\n\nlocal_time\x18\x04 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\t\x12\x0e\n\x06ticket\x18\x06 \x01(\x05\x12\r\n\x05magic\x18\x07 \x01(\x05\x12\x0e\n\x06source\x18\x08 \x01(\t\x12\x0e\n\x06symbol\x18\t \x01(\t\x12\x12\n\norder_type\x18\n \x01(\x05\x12\x0c\n\x04lots\x18\x0b \x01(\x01\x12\r\n\x05price\x18\x0c \x01(\x01\x12\n\n\x02sl\x18\r \x01(\x01\x12\n\n\x02tp\x18\x0e \x01(\x01\x12\x0e\n\x06profit\x18\x0f \x01(\x01\x12\x1a\n\x12profit_after_trade\x18\x10 \x01(\x01\x12\x0e\n\x06spread\x18\x11 \x01(\x01\x12\x0f\n\x07\x63omment\x18\x12 \x01(\t\x12\x16\n\x0eremaining_lots\x18\x13 \x01(\x01\x12\x10\n\x08slippage\x18\x14 \x01(\x01\x12\x0e\n\x06volume\x18\x15 \x01(\x05\x12\x11\n\topen_time\x18\x16 \x01(\t\x12\x14\n\x0c\x62ook_bid_vol\x18\x17 \x01(\x01\x12\x14\n\x0c\x62ook_ask_vol\x18\x18 \x01(\x01\x12\x16\n\x0e\x62ook_imbalance\x18\x19 \x01(\x01\x12\x13\n\x0bsl_hit_dist\x18\x1a \x01(\x01\x12\x13\n\x0btp_hit_dist\x18\x1b \x01(\x01\x12\x13\n\x0b\x64\x65\x63ision_id\x18\x1c \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trade_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRADEEVENT']._serialized_start=28
  _globals['_TRADEEVENT']._serialized_end=556
# @@protoc_insertion_point(module_scope)
