version: "3.8"
services:
  otel-collector:
    image: otel/opentelemetry-collector:0.87.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9464:9464"
  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686"
  zipkin:
    image: openzipkin/zipkin:2.24
    ports:
      - "9411:9411"
